apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: developer-hub-catalog
  description: Developer Hub Catalog for onboarding
spec:
  targets:
    - ./users/org.yaml
    - ./templates/*/template.yaml
